version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ~/temp/local-volumes:/app/volumes # Example for local volume mapping
      - ~/Development/apps-sdk-local-server/dist:/app/dist # Example for local dist mapping
    working_dir: /app
    environment:
      - VOLUME_PATH=~/temp/local-volumes # Add the same path as the volume path (line 7)
      - PUB_SUB_DEV_APP_SERVICE_URL=https://06960e2370f5.apps-tunnel.monday.app # Change to your exposed server URL
      - PUB_SUB_RETRY_INTERVAL_IN_SECONDS=6 # Time in seconds to retry failed requests to the local server from the queue
      - NODE_TLS_REJECT_UNAUTHORIZED=0 # Required for local development
    ports:
      - '59999:3000'
    command: node ./dist/src/app.js
